In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **Ex:1**

In [9]:
np.round(np.random.rand(5,5)*1000)

array([[909.,  92., 177., 118., 478.],
       [536., 639., 200., 906., 317.],
       [108., 601., 668., 364., 351.],
       [442., 584., 478., 340., 199.],
       [591., 142., 244., 400., 323.]])

In [6]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([1, 1, 9, 6, 9])

In [7]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([10,  1,  2,  4,  7])

In [8]:
np_matrix = np.random.rand(1000,5)
idx_choose = np.random.choice(1000,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.82816175, 0.77517508, 0.50106035, 0.66963346, 0.83655538],
       [0.98768426, 0.28575313, 0.57812007, 0.72590535, 0.49039848],
       [0.50481006, 0.90028439, 0.85457117, 0.95383648, 0.9631465 ]])

# Ex:2

In [10]:
np_matrix = np.random.rand(10,5)
roundup = np.round(np_matrix[:,4])
np_matrix[:,4] = roundup
np_matrix

array([[0.19727551, 0.05082801, 0.67747869, 0.24298665, 1.        ],
       [0.23279265, 0.0870326 , 0.35648203, 0.1873639 , 0.        ],
       [0.29190889, 0.46406608, 0.74205178, 0.76691786, 0.        ],
       [0.30887031, 0.02129526, 0.18239926, 0.6827215 , 1.        ],
       [0.96148866, 0.34694296, 0.05149243, 0.76363778, 0.        ],
       [0.19998491, 0.97730499, 0.11051338, 0.73449211, 0.        ],
       [0.14777688, 0.95496256, 0.40552839, 0.60980527, 0.        ],
       [0.9160538 , 0.51827875, 0.66105829, 0.00915269, 0.        ],
       [0.36946675, 0.90955233, 0.90268016, 0.26727891, 1.        ],
       [0.19046576, 0.65114175, 0.43340594, 0.57067394, 0.        ]])

In [11]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 1,  9,  0,  7,  7],
       [ 9,  9, 10, 10,  3],
       [ 4,  6,  7, 10,  7],
       [ 0,  1,  2,  9,  1],
       [ 7, 10,  5,  8,  1]])

# Ex:3

In [12]:
np_matrix = np.random.randint(3,size=(6,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[0, 1, 1, 0, 2],
       [0, 1, 0, 1, 2],
       [1, 0, 1, 2, 2],
       [1, 1, 2, 2, 0],
       [2, 2, 1, 2, 0]])

# Ex:4

In [13]:
np_rand = np.random.randint(10,size = (10,5))
np_rand

array([[4, 9, 0, 5, 4],
       [5, 9, 4, 5, 8],
       [2, 5, 4, 8, 9],
       [9, 2, 5, 8, 3],
       [4, 9, 1, 5, 3],
       [2, 8, 6, 5, 9],
       [7, 4, 2, 8, 0],
       [1, 8, 1, 3, 3],
       [9, 3, 7, 2, 1],
       [4, 3, 2, 4, 8]])

In [14]:
label_vector = np.random.randint(2,size = 10)
label_vector

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0])

In [15]:
train_data = (label_vector == 0)
np_rand[train_data]

array([[4, 9, 0, 5, 4],
       [5, 9, 4, 5, 8],
       [2, 5, 4, 8, 9],
       [4, 9, 1, 5, 3],
       [7, 4, 2, 8, 0],
       [9, 3, 7, 2, 1],
       [4, 3, 2, 4, 8]])

In [16]:
test_data = (label_vector == 1)
np_rand[test_data]

array([[9, 2, 5, 8, 3],
       [2, 8, 6, 5, 9],
       [1, 8, 1, 3, 3]])

# Ex:5

In [17]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[2, 3, 4, 1, 4],
       [1, 3, 1, 2, 1],
       [4, 4, 2, 2, 4],
       [5, 2, 2, 3, 1],
       [1, 2, 5, 4, 3]])

In [18]:
np.sort(data[0,:]*-1)

array([-4, -4, -3, -2, -1])

# Ex:6

In [19]:
np_test= np.arange(25).reshape(5,5)
np_test [np_test%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# Ex:7

In [20]:
np_test= np.arange(25).reshape(5,5)
np_test[np.fill_diagonal(np_test,0)]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16, 17,  0, 19],
        [20, 21, 22, 23,  0]]])